#!/usr/bin/env bash

. $CONFIG

EditConfig() {

    # https://stackoverflow.com/a/2464883
    sed -i "s#\($1 *= *\).*#\1$2#" $3
}

MakeLog() {

    scriptName=${0##*/}
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    echo "== $scriptName $timestamp $1"
}

