#!/usr/bin/env bash

set -e
export WORKDIR=$(cd $(dirname $0) && pwd)
export JSONPARSER=$WORKDIR/jsonParser.py
if [ ! -f "$WORKDIR/config" ]; then
    cp $WORKDIR/config.template $WORKDIR/config
fi
export CONFIG=$WORKDIR/config

. $WORKDIR/common

# options and values
export aFlag=0
export cFlag=0

export aVal=0

Usage() {
    echo $'Usage: \n\nCommands: \n'
}
Help() {

    echo $'Cloodle (Moodle CLI)\nGitHub: \nVersion:' $(cat $WORKDIR/VERSION) $'\n'
    Usage
}

# https://stackoverflow.com/a/5230306
if ! options=$(getopt -u -o ca: -l course,asgn: -- "$@"); then
    exit 1
fi

set -- $options

while [ $# -gt 0 ]; do
    
    # echo "in loop $0 $1 $2"
    case $1 in
        -c|--course)
            cFlag=1            
            ;;
        -a|--asgn)
            aFlag=1
            aVal=$2
            shift
            ;;
        (--)
            shift
            break
            ;;
        (-*)
            echo "$0: error - unrecognized option $1" 1>&2; 
            Usage
            exit 1
            ;;
        (*)
            Usage
            break;;
    esac
    shift
done

case "$1" in
    help)
        Help
        exit 0
        ;;
    login)
        . $WORKDIR/commands/lmsLogin
        Login
        exit 0
        ;;
    display)
        . $WORKDIR/commands/lmsDisplay
        Display
        exit 0
        ;;
    *)
        echo "Invalid command $1!"
        Usage
        exit 1
        ;;
esac
