#!/usr/bin/env bash

set -e
export WORKDIR=$(cd $(dirname $0) && pwd)
if [ ! -f "$WORKDIR/config" ]; then
    cp $WORKDIR/config.template $WORKDIR/config
fi
export CONFIG=$WORKDIR/config

. $WORKDIR/common

# options and values
export cFlag=0 #course flag
export aFlag=0 #asgn flag
export pFlag=0 #path flag
export fFlag=0 #force flag

export cVal=0 #id
export aVal=0 #id
export pVal=0 #path

Usage() {    
cat << END 
Usage: lms [options...] [command] 

-c, --course <value>
    Set course-id to <value>

-a,--asgn <value>
    Set assignment-id to <value>

-p,--path <value>
    Set path to <value>

-f,--force
    Reset data before action


Commands:

[help]
    Help

[(-f) login]
    Enter credentials
    Use required option to reset domain name

[(-c) display]
    Display current enrolled courses
    Use required option to display assignments specific to course

[(-p) -a upload]
    Display assignment details
    Use required option to upload a single file to assignment 

[(-p) -a download]
    Display assignment file names
    Use required option to specify download path
    
END
}
Help() {
    echo $'Cloodle (Moodle CLI)\nGitHub: https://github.com/sriramun/cloodle\nVersion:' $(cat $WORKDIR/VERSION) $'\n'
    Usage
}

# https://stackoverflow.com/a/5230306
if ! options=$(getopt -u -o fp:a:c: -l force,path:,asgn:,course: -- "$@"); then
    exit 1
fi

set -- $options

while [ $# -gt 0 ]; do
    
    # echo "in loop $0 $1 $2"
    case $1 in
        -c|--course)
            cFlag=1
            cVal=$2
            shift
            ;;
        -a|--asgn)
            aFlag=1
            aVal=$2
            shift
            ;;
        -p|--path)
            pFlag=1
            pVal=$2
            shift
            ;;
        -f|--force)
            fFlag=1
            ;;
        (--)
            shift
            break
            ;;
        (-*)
            echo "$0: error - unrecognized option $1" 1>&2; 
            echo "Use the 'help' command for usage information"
            exit 1
            ;;
        (*)
            echo "Use the 'help' command for usage information"
            break;;
    esac
    shift
done

case "$1" in
    help)
        Help
        exit 0
        ;;
    login)
        . $WORKDIR/commands/Login
        Login
        exit 0
        ;;
    display)
        . $WORKDIR/commands/Display
        Display
        exit 0
        ;;
    upload)
        . $WORKDIR/commands/Upload
        Upload
        exit 0
        ;;
    download)
        . $WORKDIR/commands/Download
        Download
        exit 0
        ;;
    *)
        echo "$0: error - unrecognized command $1" 1>&2;
        echo "Use the 'help' command for usage information"
        exit 1
        ;;
esac
