#!/usr/bin/env bash

# https://stackoverflow.com/a/33077717
Parser() {
python3 <(
cat << "END"

import os
import sys
import json

#try:

data = json.load(sys.stdin)

aFlag = int(os.environ['aFlag'])

if not aFlag:
    
    print('ID] Course Name')

    for i in data['courses']:
        print(str(i['id']), end='] ')
        print(i['fullname'])

else:
    
    print('ID] Assignment Name')

    for i in data:
        for j in i['modules']:
            if j['modname'] == 'assign':
                print(str(j['instance']), end='] ')
                print(j['name'])

#except:
#    print("Oops")

END
)
}

Display() {

    . $WORKDIR/common

    if [[ ! $WSTOKEN || ! $DOMAIN ]]; then
        echo "Login first!"
        exit 1
    fi

    # https://unix.stackexchange.com/a/164548
    IFS=

    if [ $aFlag == 0 ]; then
        echo -e $(curl --silent \
             -d wstoken=${WSTOKEN} \
             -d wsfunction="core_course_get_enrolled_courses_by_timeline_classification" \
             -d classification="inprogress" \
             "${DOMAIN}/webservice/rest/server.php?moodlewsrestformat=json" | \
             Parser)
    else
        echo -e $(curl --silent \
           -d wstoken=${WSTOKEN} \
           -d wsfunction="core_course_get_contents" \
           -d courseid=${aVal} \
           "${DOMAIN}/webservice/rest/server.php?moodlewsrestformat=json" | \
           #python3 -m json.tool)
           Parser)
    fi
}
