#!/usr/bin/env bash


Parser() {
python3 <(
cat << "END"

import os
import sys
import json

#try: 
data = json.load(sys.stdin)

print(data['token']) 

#except: 
#    print("")

END
)
}

Login() {
    
    . $WORKDIR/common

    if [ ! $DOMAIN ]; then
        read -p "Domain Name: " domain
        EditConfig DOMAIN $domain $CONFIG
    fi
    
    read -p "Username: " username
    read -s -p "Password: " password; echo

    echo ${DOMAIN}
    token=$(curl --silent \
        -d username=${username} \
        -d password=${password} \
        "${DOMAIN}/login/token.php?service=moodle_mobile_app" | \
        Parser)
        #${JSONPARSER} Login)
    
    if [ $token ]; then
        EditConfig WSTOKEN $token $CONFIG
    else
        echo "Invalid credentials!"
    fi
}
