#!/usr/bin/env bash


Parser() {
python3 <(
cat << "END"

import os
import sys
import json

try: 
    data = json.load(sys.stdin)

    print(data['token']) 

except: 
    print("")

END
)
}

Login() {
    
    . $WORKDIR/common

    domain=${DOMAIN}

    if [[ ! $DOMAIN || $fFlag == 1 ]]; then
        read -p "URL: " domain
        EditConfig DOMAIN $domain $CONFIG
    fi

    read -p "Username: " username
    read -s -p "Password: " password; echo

    # need to enable redirect feature
    token=$(curl --silent \
        -d username=${username} \
        -d password=${password} \
        "${domain}/login/token.php?service=moodle_mobile_app" | \
        Parser)
    
    if [ $token ]; then
        EditConfig WSTOKEN $token $CONFIG
        echo "Login successful!"
    else
        echo "Invalid credentials!"
        exit 1
    fi
}
